// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheWay.Api.Data;

#nullable disable

namespace TheWay.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520140119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheWay.Api.Models.Domain.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AvoidingEvil")
                        .HasColumnType("boolean");

                    b.Property<bool>("BibleReading")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GoodDeeds")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<bool>("Prayer")
                        .HasColumnType("boolean");

                    b.Property<bool>("SpiritualBooks")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LogDate");

                    b.HasIndex("UserId", "LogDate")
                        .IsUnique();

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("TheWay.Api.Models.Domain.PriestQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PublishedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PublishedBy");

                    b.ToTable("PriestQuotes");
                });

            modelBuilder.Entity("TheWay.Api.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FormalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SpiritualName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "priest@theway.app",
                            FormalName = "Administrator",
                            IsActive = true,
                            MustChangePassword = true,
                            PasswordHash = "$2a$11$MBc2AuN2cmICMosY9jzFDe88jo.UWX/nlxDkEdDeB4DI4JrdDRQFi",
                            Role = "Priest",
                            SpiritualName = "ቀሲስ"
                        });
                });

            modelBuilder.Entity("TheWay.Api.Models.Domain.DailyLog", b =>
                {
                    b.HasOne("TheWay.Api.Models.Domain.User", "User")
                        .WithMany("DailyLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheWay.Api.Models.Domain.PriestQuote", b =>
                {
                    b.HasOne("TheWay.Api.Models.Domain.User", "Publisher")
                        .WithMany("PublishedQuotes")
                        .HasForeignKey("PublishedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("TheWay.Api.Models.Domain.User", b =>
                {
                    b.Navigation("DailyLogs");

                    b.Navigation("PublishedQuotes");
                });
#pragma warning restore 612, 618
        }
    }
}
